### PR TITLE
Fix freezing UI while switching between instances

### LINKED ISSUE #388: Switching between instances freezes UI
Switching between instances freezes UI:
https://www.screencast.com/t/aUuTYe3CA

### PR DESCRIPTION
**Pull request by ViacheslavAfanasyev**
closes #388

### CODE REVIEW

File: src/SIM.Instances/PartiallyCachedInstance.cs [hunk 1]
```diff
@@ -152,5 +164,13 @@ private void ClearCache([CanBeNull] object sender, [CanBeNull] FileSystemEventAr
     }
 
     #endregion
+
+    #region Protected methods
+    protected void OnPropertyChanged([CallerMemberName] string name = null)
```
Comment (AndreyFilchenkov) [inline src/SIM.Instances/PartiallyCachedInstance.cs]: The 'PartiallyCachedInstance.cs' is sealed class. So there are not any benefits to having a protected method(OnPropertyChanged) in it.
Please consider changing the access modifier to private.

Comment (ViacheslavAfanasyev) [reply src/SIM.Instances/PartiallyCachedInstance.cs]: Fixed
