### PR TITLE
#424: Provide meaningful messages in validators

### LINKED ISSUE #424: Provide meaningful messages in validators
all error messages must be clear to understand what is wrong and where.
add success messages.

### PR DESCRIPTION
**Pull request by AndreyFilchenkov**
closes #424

### CODE REVIEW

File: src/SIM.Sitecore9Installer/Validation/Validators/CmDdsPatchSiteNameValidator.cs [hunk 1]
```diff
@@ -12,6 +12,8 @@ public class CmDdsPatchSiteNameValidator : IValidator
 
     public Dictionary<string, string> Data { get; set; }
 
+    public virtual string SuccessMessage => "'SiteName' value was set properly for 'cm-dds-patch' installation task.";
```
Comment (DmitryKolinchuk) [inline src/SIM.Sitecore9Installer/Validation/Validators/CmDdsPatchSiteNameValidator.cs:15]: To make it consistent with the error message it should be: **'SiteName' value was set properly for 'sitecore-xp1-cm' and 'sitecore-XP1-cm-dds-patch' installation tasks.**

Comment (AndreyFilchenkov) [reply src/SIM.Sitecore9Installer/Validation/Validators/CmDdsPatchSiteNameValidator.cs]: Done
